"""create delivery options table

Revision ID: 07723f7e93a6
Revises: dbea86d40b87
Create Date: 2026-06-05 10:58:52.296431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07723f7e93a6'
down_revision: Union[str, Sequence[str], None] = 'dbea86d40b87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('charge', sa.Integer(), nullable=False),
    sa.Column('delivery_days', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_options_id'), 'delivery_options', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_delivery_options_id'), table_name='delivery_options')
    op.drop_table('delivery_options')
    # ### end Alembic commands ###
