"""add status column to addresses

Revision ID: dbea86d40b87
Revises: 1a7f5df86db0
Create Date: 2026-06-04 13:16:23.543983

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbea86d40b87'
down_revision: Union[str, Sequence[str], None] = '1a7f5df86db0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'addresses',
        sa.Column(
            'status',
            sa.String(length=20),
            nullable=False,
            server_default='Home'
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addresses', 'status')
    # ### end Alembic commands ###
